extension ProblemaGES {
    static let todos: [ProblemaGES] = [
        ProblemaGES(
            id: 1,
            nombre: "Insuficiencia Renal Crónica Terminal",
            categoria: .renalUrologico,
            descripcion: "Enfermedad renal crónica en etapa terminal que requiere terapia de sustitución renal (diálisis o trasplante).",
            poblacionObjetivo: "Todas las personas.",
            sospechaDiagnostica: "Paciente con VFG < 15 mL/min/1.73m², elevación persistente de creatinina, síntomas urémicos (náuseas, prurito, fatiga extrema, edema refractario).",
            confirmacionDiagnostica: "Creatinina sérica, clearance de creatinina, ecografía renal, biopsia renal cuando corresponda. VFG < 15 mL/min confirma etapa 5.",
            garantiaOportunidad: "Acceso a diálisis dentro de 7 días desde la indicación médica. Trasplante renal según disponibilidad de órgano.",
            tratamiento: "Hemodiálisis, diálisis peritoneal o trasplante renal. Manejo de complicaciones: anemia, hiperparatiroidismo, hipertensión.",
            seguimiento: "Control mensual en hemodiálisis. Evaluación trimestral de acceso vascular. Laboratorio mensual (BUN, creatinina, electrolitos, hemograma)."
        ),
        ProblemaGES(
            id: 2,
            nombre: "Cardiopatías Congénitas Operables en Menores de 15 Años",
            categoria: .cardiovascular,
            descripcion: "Malformaciones estructurales del corazón presentes desde el nacimiento que son susceptibles de corrección quirúrgica.",
            poblacionObjetivo: "Menores de 15 años con cardiopatía congénita operable.",
            sospechaDiagnostica: "Soplo cardíaco patológico, cianosis, dificultad respiratoria, falla de medro, saturación de oxígeno disminuida, taquicardia inexplicada.",
            confirmacionDiagnostica: "Ecocardiograma Doppler color. En casos complejos: cateterismo cardíaco, angioTAC o resonancia magnética cardíaca.",
            garantiaOportunidad: "Diagnóstico dentro de 180 días. Cirugía dentro de 365 días desde confirmación diagnóstica. Urgencias según necesidad clínica.",
            tratamiento: "Corrección quirúrgica de la cardiopatía (cierre de CIA, CIV, corrección de tetralogía de Fallot, etc.). Manejo médico preoperatorio.",
            seguimiento: "Control cardiológico periódico post cirugía. Ecocardiograma de seguimiento. Profilaxis de endocarditis según indicación."
        ),
        ProblemaGES(
            id: 3,
            nombre: "Cáncer Cervicouterino",
            categoria: .oncologico,
            descripcion: "Neoplasia maligna del cuello uterino. Incluye etapificación, tratamiento y seguimiento.",
            poblacionObjetivo: "Mujeres de 15 años y más.",
            sospechaDiagnostica: "PAP alterado (NIE II, NIE III, carcinoma in situ o invasor), sangrado genital anormal, sinusorragia, flujo vaginal persistente.",
            confirmacionDiagnostica: "Colposcopía y biopsia cervical. Etapificación con examen físico, TAC, resonancia magnética pélvica.",
            garantiaOportunidad: "Confirmación diagnóstica dentro de 30 días desde sospecha. Inicio de tratamiento dentro de 30 días desde etapificación.",
            tratamiento: "Según etapa: conización, histerectomía radical, radioterapia, quimioterapia o combinaciones. Etapas IA1: conización. Etapas IB-IVA: radio-quimioterapia.",
            seguimiento: "Control cada 3 meses los primeros 2 años, luego semestral hasta 5 años. PAP y examen ginecológico en cada control."
        ),
        ProblemaGES(
            id: 4,
            nombre: "Alivio del Dolor y Cuidados Paliativos por Cáncer Avanzado",
            categoria: .oncologico,
            descripcion: "Manejo integral del dolor y síntomas en pacientes con cáncer avanzado sin posibilidad curativa.",
            poblacionObjetivo: "Todas las personas con cáncer avanzado con dolor y/o síntomas que requieran paliación.",
            sospechaDiagnostica: "Paciente con diagnóstico de cáncer avanzado que presenta dolor (EVA ≥ 4), disnea, náuseas u otros síntomas refractarios.",
            confirmacionDiagnostica: "Diagnóstico oncológico confirmado con etapificación avanzada (etapa III-IV o recurrencia sin opción curativa).",
            garantiaOportunidad: "Acceso a tratamiento del dolor dentro de 5 días desde la solicitud. Atención domiciliaria cuando corresponda.",
            tratamiento: "Escalera analgésica OMS: AINES, opioides débiles, opioides potentes. Coadyuvantes (antidepresivos, anticonvulsivantes). Manejo de síntomas asociados.",
            seguimiento: "Visitas domiciliarias regulares. Evaluación periódica del dolor con escalas validadas. Ajuste de analgesia según necesidad."
        ),
        ProblemaGES(
            id: 5,
            nombre: "Infarto Agudo del Miocardio",
            categoria: .cardiovascular,
            descripcion: "Necrosis del músculo cardíaco por oclusión aguda de arteria coronaria. Incluye SDST y SSDST.",
            poblacionObjetivo: "Todas las personas de 15 años y más.",
            sospechaDiagnostica: "Dolor torácico opresivo de más de 20 minutos, irradiado a brazo izquierdo, mandíbula o epigastrio. Disnea, diaforesis, náuseas. ECG con supradesnivel ST o nuevo BCRI.",
            confirmacionDiagnostica: "ECG de 12 derivaciones, troponinas cardíacas seriadas (troponina I o T ultrasensible), CK-MB. Coronariografía.",
            garantiaOportunidad: "Confirmación diagnóstica inmediata. Trombolisis dentro de 30 minutos o angioplastía primaria dentro de 90 minutos desde el diagnóstico.",
            tratamiento: "Reperfusión: angioplastía primaria (preferida) o trombolisis. Antiagregación dual (AAS + clopidogrel/ticagrelor). Anticoagulación. Betabloqueadores, IECA/ARA II, estatinas.",
            seguimiento: "Control cardiológico a los 30 días, 3 meses y luego anual. Rehabilitación cardíaca. Control de factores de riesgo cardiovascular."
        ),
        ProblemaGES(
            id: 6,
            nombre: "Diabetes Mellitus Tipo 1",
            categoria: .endocrinoMetabolico,
            descripcion: "Enfermedad autoinmune con destrucción de células beta pancreáticas y déficit absoluto de insulina.",
            poblacionObjetivo: "Todas las personas.",
            sospechaDiagnostica: "Polidipsia, poliuria, polifagia, baja de peso inexplicada, cetoacidosis diabética. Debut frecuente en niños y adolescentes.",
            confirmacionDiagnostica: "Glicemia en ayunas ≥ 126 mg/dL o glicemia casual ≥ 200 mg/dL con síntomas. Péptido C bajo, anticuerpos anti-GAD, anti-IA2.",
            garantiaOportunidad: "Confirmación diagnóstica dentro de 30 días. Inicio de tratamiento desde confirmación.",
            tratamiento: "Insulinoterapia intensificada (basal-bolo o bomba de insulina). Automonitoreo de glicemia. Educación en conteo de carbohidratos.",
            seguimiento: "Control cada 3 meses con HbA1c. Screening anual de complicaciones: fondo de ojo, microalbuminuria, perfil lipídico, función renal."
        ),
        ProblemaGES(
            id: 7,
            nombre: "Diabetes Mellitus Tipo 2",
            categoria: .endocrinoMetabolico,
            descripcion: "Enfermedad metabólica crónica con resistencia a insulina y déficit relativo de secreción. Principal causa de morbimortalidad cardiovascular.",
            poblacionObjetivo: "Personas de 15 años y más.",
            sospechaDiagnostica: "Glicemia en ayunas ≥ 100 mg/dL, factores de riesgo (obesidad, antecedentes familiares, síndrome metabólico), polidipsia, poliuria.",
            confirmacionDiagnostica: "Glicemia en ayunas ≥ 126 mg/dL en 2 ocasiones, PTGO ≥ 200 mg/dL a las 2 horas, o HbA1c ≥ 6.5%.",
            garantiaOportunidad: "Confirmación diagnóstica dentro de 45 días. Inicio de tratamiento desde confirmación.",
            tratamiento: "Cambios en estilo de vida, metformina como primera línea. Asociar sulfonilureas, iDPP4, iSGLT2 o insulina según HbA1c y comorbilidades.",
            seguimiento: "Control cada 3-4 meses con HbA1c. Screening anual de complicaciones microvasculares y macrovasculares. Examen de pie diabético."
        ),
        ProblemaGES(
            id: 8,
            nombre: "Cáncer de Mama en Personas de 15 Años y Más",
            categoria: .oncologico,
            descripcion: "Neoplasia maligna de la glándula mamaria. Incluye diagnóstico, etapificación, tratamiento y seguimiento.",
            poblacionObjetivo: "Personas de 15 años y más (principalmente mujeres).",
            sospechaDiagnostica: "Nódulo mamario palpable, mamografía BIRADS 4 o 5, retracción cutánea o del pezón, secreción hemática por pezón, adenopatía axilar.",
            confirmacionDiagnostica: "Biopsia core (trucut) o biopsia excisional. Estudio histológico con receptores hormonales, HER2, Ki67. Etapificación con imágenes.",
            garantiaOportunidad: "Confirmación diagnóstica dentro de 45 días desde sospecha. Inicio de tratamiento dentro de 30 días desde etapificación.",
            tratamiento: "Según etapa y biología: cirugía conservadora o mastectomía, quimioterapia neoadyuvante/adyuvante, radioterapia, hormonoterapia, terapia anti-HER2.",
            seguimiento: "Control cada 3-4 meses los primeros 2 años, semestral hasta 5 años, luego anual. Mamografía anual."
        ),
        ProblemaGES(
            id: 9,
            nombre: "Disrafias Espinales",
            categoria: .neurologico,
            descripcion: "Defectos del cierre del tubo neural (mielomeningocele, meningocele, espina bífida). Requiere manejo multidisciplinario.",
            poblacionObjetivo: "Todas las personas con disrafia espinal desde el nacimiento.",
            sospechaDiagnostica: "Diagnóstico prenatal por ecografía (defecto de cierre del tubo neural). Al nacer: masa dorsal, déficit neurológico de extremidades inferiores.",
            confirmacionDiagnostica: "Ecografía prenatal, alfafetoproteína elevada. Postnatal: RNM de columna y cerebro, evaluación neuroquirúrgica.",
            garantiaOportunidad: "Tratamiento quirúrgico dentro de las primeras 72 horas de vida en casos abiertos. Seguimiento multidisciplinario.",
            tratamiento: "Cierre quirúrgico precoz del defecto. Derivación ventrículo-peritoneal si hay hidrocefalia. Rehabilitación motora, manejo urológico.",
            seguimiento: "Control multidisciplinario: neurocirugía, urología, traumatología, fisiatría. Evaluación urodinámica periódica."
        ),
        ProblemaGES(
            id: 10,
            nombre: "Tratamiento Quirúrgico de Escoliosis en Menores de 25 Años",
            categoria: .musculoesqueletico,
            descripcion: "Corrección quirúrgica de deformidad espinal estructural severa en pacientes jóvenes.",
            poblacionObjetivo: "Menores de 25 años con escoliosis que requiere tratamiento quirúrgico.",
            sospechaDiagnostica: "Asimetría de hombros, escápulas o cintura. Test de Adams positivo (giba costal). Curvatura visible de la columna.",
            confirmacionDiagnostica: "Radiografía de columna total (teleradiografía). Ángulo de Cobb ≥ 25° para tratamiento ortopédico, ≥ 45-50° para indicación quirúrgica.",
            garantiaOportunidad: "Confirmación diagnóstica dentro de 60 días. Cirugía dentro de 365 días desde indicación quirúrgica.",
            tratamiento: "Artrodesis vertebral con instrumentación posterior. Corsé en curvas entre 25-45° en pacientes en crecimiento.",
            seguimiento: "Control radiológico a los 3, 6 y 12 meses post cirugía. Luego anual hasta madurez esquelética."
        ),
        ProblemaGES(
            id: 11,
            nombre: "Tratamiento Quirúrgico de Cataratas",
            categoria: .oftalmologico,
            descripcion: "Opacificación del cristalino que produce disminución de agudeza visual. Tratamiento quirúrgico con implante de lente intraocular.",
            poblacionObjetivo: "Todas las personas.",
            sospechaDiagnostica: "Disminución progresiva de agudeza visual, visión borrosa, deslumbramiento, dificultad para leer o conducir.",
            confirmacionDiagnostica: "Examen oftalmológico con biomicroscopía (lámpara de hendidura). Agudeza visual corregida que afecta funcionalidad.",
            garantiaOportunidad: "Confirmación diagnóstica dentro de 180 días. Cirugía dentro de 365 días desde indicación.",
            tratamiento: "Facoemulsificación con implante de lente intraocular. Cirugía ambulatoria con anestesia local.",
            seguimiento: "Control postoperatorio al día 1, semana 1, mes 1 y mes 3. Refracción definitiva a los 2-3 meses."
        ),
        ProblemaGES(
            id: 12,
            nombre: "Endoprótesis Total de Cadera en Personas de 65 Años y Más",
            categoria: .musculoesqueletico,
            descripcion: "Reemplazo articular total de cadera en pacientes con artrosis severa y limitación funcional importante.",
            poblacionObjetivo: "Personas de 65 años y más con artrosis de cadera con limitación funcional severa.",
            sospechaDiagnostica: "Dolor crónico de cadera con limitación funcional severa, cojera, dificultad para caminar y realizar actividades de la vida diaria.",
            confirmacionDiagnostica: "Radiografía de pelvis AP y axial de cadera. Artrosis grado 3-4 de Kellgren-Lawrence con indicación quirúrgica.",
            garantiaOportunidad: "Confirmación diagnóstica dentro de 180 días. Cirugía dentro de 365 días desde indicación.",
            tratamiento: "Artroplastía total de cadera (prótesis cementada o no cementada según edad y calidad ósea). Profilaxis antitrombótica.",
            seguimiento: "Rehabilitación kinésica precoz. Control a las 6 semanas, 3 meses, 6 meses y anual. Radiografía de control."
        ),
        ProblemaGES(
            id: 13,
            nombre: "Fisura Labiopalatina",
            categoria: .neonatalPediatrico,
            descripcion: "Malformación congénita del labio y/o paladar que requiere tratamiento quirúrgico y rehabilitación multidisciplinaria.",
            poblacionObjetivo: "Todas las personas desde el nacimiento.",
            sospechaDiagnostica: "Diagnóstico evidente al nacer: fisura de labio, paladar o ambos. Puede diagnosticarse prenatalmente por ecografía.",
            confirmacionDiagnostica: "Examen clínico al nacer. Clasificación de la fisura (labial, palatina, labiopalatina, uni o bilateral).",
            garantiaOportunidad: "Tratamiento ortopédico prequirúrgico desde el nacimiento. Cirugía de labio a los 3-6 meses, paladar a los 12-18 meses.",
            tratamiento: "Queiloplastía (cierre de labio), palatoplastía (cierre de paladar). Ortopedia prequirúrgica. Tratamiento ortodóncico, fonoaudiológico.",
            seguimiento: "Seguimiento multidisciplinario: cirujano, ortodoncista, fonoaudiólogo, otorrino, psicólogo. Hasta completar crecimiento craneofacial."
        ),
        ProblemaGES(
            id: 14,
            nombre: "Cáncer en Menores de 15 Años",
            categoria: .oncologico,
            descripcion: "Todos los tipos de cáncer diagnosticados en menores de 15 años. Incluye leucemias, tumores sólidos y del SNC.",
            poblacionObjetivo: "Menores de 15 años.",
            sospechaDiagnostica: "Palidez, fiebre prolongada, adenopatías, hepatoesplenomegalia, dolor óseo, masa abdominal, cefalea persistente con vómitos, leucocoria.",
            confirmacionDiagnostica: "Hemograma, mielograma, biopsia tumoral, imágenes (TAC, RNM), marcadores tumorales según tipo de cáncer.",
            garantiaOportunidad: "Confirmación diagnóstica dentro de 14 días desde sospecha. Inicio de tratamiento dentro de 14 días desde confirmación.",
            tratamiento: "Según tipo: quimioterapia, cirugía, radioterapia o combinaciones. Protocolos PINDA (Programa Infantil Nacional de Drogas Antineoplásicas).",
            seguimiento: "Según protocolo específico. Vigilancia de recaída y efectos tardíos del tratamiento. Seguimiento hasta 5 años post tratamiento."
        ),
        ProblemaGES(
            id: 15,
            nombre: "Esquizofrenia",
            categoria: .saludMental,
            descripcion: "Trastorno psicótico crónico con síntomas positivos (alucinaciones, delirios) y negativos (aplanamiento afectivo, abulia).",
            poblacionObjetivo: "Personas de 15 años y más con primer episodio.",
            sospechaDiagnostica: "Alucinaciones auditivas, ideas delirantes, desorganización del pensamiento, conducta bizarra, aislamiento social progresivo, deterioro funcional.",
            confirmacionDiagnostica: "Evaluación psiquiátrica según criterios CIE-10/DSM-5. Descartar causas orgánicas (neuroimagen, laboratorio). Duración de síntomas > 1 mes.",
            garantiaOportunidad: "Confirmación diagnóstica dentro de 30 días. Inicio de tratamiento desde confirmación.",
            tratamiento: "Antipsicóticos atípicos (risperidona, olanzapina, quetiapina). Intervención psicosocial, rehabilitación, terapia familiar. Clozapina en refractariedad.",
            seguimiento: "Control psiquiátrico mensual inicial, luego según estabilidad. Monitoreo de efectos metabólicos de antipsicóticos. Rehabilitación psicosocial."
        ),
        ProblemaGES(
            id: 16,
            nombre: "Cáncer de Testículo en Personas de 15 Años y Más",
            categoria: .oncologico,
            descripcion: "Neoplasia maligna testicular. Incluye seminomas y no seminomas. Alta tasa de curación con tratamiento adecuado.",
            poblacionObjetivo: "Personas de 15 años y más con testículos.",
            sospechaDiagnostica: "Masa testicular indolora, aumento de volumen testicular, pesadez escrotal. Marcadores tumorales: AFP, beta-HCG, LDH.",
            confirmacionDiagnostica: "Ecografía testicular, marcadores tumorales, TAC tórax-abdomen-pelvis. Orquiectomía radical inguinal diagnóstica y terapéutica.",
            garantiaOportunidad: "Confirmación dentro de 30 días. Tratamiento dentro de 30 días post confirmación.",
            tratamiento: "Orquiectomía radical inguinal. Según etapa y tipo: vigilancia activa, quimioterapia (BEP), radioterapia (seminoma), linfadenectomía retroperitoneal.",
            seguimiento: "Marcadores tumorales y TAC según protocolo. Seguimiento estrecho los primeros 2 años. Preservación de fertilidad previa al tratamiento."
        ),
        ProblemaGES(
            id: 17,
            nombre: "Linfomas en Personas de 15 Años y Más",
            categoria: .oncologico,
            descripcion: "Neoplasias del sistema linfático. Incluye linfoma de Hodgkin y linfomas no Hodgkin.",
            poblacionObjetivo: "Personas de 15 años y más.",
            sospechaDiagnostica: "Adenopatías indoloras persistentes (> 2 cm por > 4 semanas), síntomas B (fiebre, sudoración nocturna, baja de peso > 10%), prurito generalizado.",
            confirmacionDiagnostica: "Biopsia ganglionar excisional con estudio histopatológico e inmunohistoquímica. Etapificación con PET-CT o TAC.",
            garantiaOportunidad: "Confirmación dentro de 30 días. Inicio de tratamiento dentro de 30 días post etapificación.",
            tratamiento: "Hodgkin: ABVD ± radioterapia. No Hodgkin: según subtipo, R-CHOP para linfomas B difusos de células grandes. Trasplante en recaída.",
            seguimiento: "Control cada 3 meses los primeros 2 años, semestral hasta 5 años. PET-CT de evaluación de respuesta."
        ),
        ProblemaGES(
            id: 18,
            nombre: "Síndrome de Inmunodeficiencia Adquirida VIH/SIDA",
            categoria: .infeccioso,
            descripcion: "Infección por VIH. Incluye diagnóstico, tratamiento antirretroviral, manejo de infecciones oportunistas y seguimiento.",
            poblacionObjetivo: "Todas las personas.",
            sospechaDiagnostica: "Conductas de riesgo, infecciones oportunistas, síndrome retroviral agudo, adenopatías generalizadas, baja de peso, diarrea crónica.",
            confirmacionDiagnostica: "Test de ELISA para VIH reactivo confirmado con segundo ELISA o Western Blot. Carga viral VIH, recuento de CD4.",
            garantiaOportunidad: "Confirmación dentro de 60 días. Inicio de TAR desde confirmación (idealmente en la primera consulta de especialidad).",
            tratamiento: "Terapia antirretroviral (TAR) combinada: 2 INTR + 1 inhibidor de integrasa (dolutegravir). Profilaxis de infecciones oportunistas según CD4.",
            seguimiento: "Carga viral y CD4 al inicio, a los 3 y 6 meses, luego cada 6 meses. Meta: carga viral indetectable. Screening de comorbilidades."
        ),
        ProblemaGES(
            id: 19,
            nombre: "Infección Respiratoria Aguda (IRA) de Manejo Ambulatorio en Menores de 5 Años",
            categoria: .respiratorio,
            descripcion: "Infecciones del tracto respiratorio (resfrío, faringitis, bronquitis, síndrome bronquial obstructivo) de manejo ambulatorio.",
            poblacionObjetivo: "Menores de 5 años.",
            sospechaDiagnostica: "Tos, fiebre, congestión nasal, sibilancias, dificultad respiratoria leve, rinorrea. Sin signos de gravedad.",
            confirmacionDiagnostica: "Diagnóstico clínico. Score de Tal para evaluar severidad del síndrome bronquial obstructivo. Radiografía solo si sospecha de neumonía.",
            garantiaOportunidad: "Atención dentro de 24 horas desde consulta en atención primaria.",
            tratamiento: "Según diagnóstico: antipiréticos, hidratación, salbutamol en SBO (según Score de Tal), corticoides en laringitis. Antibióticos solo si bacteriana.",
            seguimiento: "Control a las 24-48 horas en SBO. Educación a padres sobre signos de alarma. Derivar si hay deterioro clínico."
        ),
        ProblemaGES(
            id: 20,
            nombre: "Neumonía Adquirida en la Comunidad de Manejo Ambulatorio en Personas de 65 Años y Más",
            categoria: .respiratorio,
            descripcion: "Infección del parénquima pulmonar adquirida en la comunidad. Manejo ambulatorio en pacientes sin criterios de hospitalización.",
            poblacionObjetivo: "Personas de 65 años y más.",
            sospechaDiagnostica: "Tos productiva, fiebre, disnea, dolor torácico pleurítico, crepitaciones a la auscultación. En adultos mayores puede presentarse con confusión.",
            confirmacionDiagnostica: "Radiografía de tórax con infiltrado pulmonar nuevo. Laboratorio: hemograma, PCR, función renal. Clasificar con CURB-65.",
            garantiaOportunidad: "Confirmación diagnóstica dentro de 48 horas. Inicio de tratamiento inmediato desde confirmación.",
            tratamiento: "Amoxicilina 1g cada 8 horas por 7 días, o amoxicilina/ácido clavulánico. Macrólidos si alergia a penicilina. Hidratación y reposo.",
            seguimiento: "Control clínico a las 48 horas. Radiografía de control a las 6 semanas. Vacunación antineumocócica e influenza."
        ),
        ProblemaGES(
            id: 21,
            nombre: "Hipertensión Arterial Primaria o Esencial en Personas de 15 Años y Más",
            categoria: .cardiovascular,
            descripcion: "Elevación crónica de la presión arterial sistémica. Principal factor de riesgo cardiovascular modificable.",
            poblacionObjetivo: "Personas de 15 años y más.",
            sospechaDiagnostica: "PA ≥ 140/90 mmHg en toma casual. Cefalea, tinitus, mareos. Frecuente hallazgo incidental en control de salud.",
            confirmacionDiagnostica: "Promedio de 2 o más mediciones en 2 o más controles con PA ≥ 140/90 mmHg. MAPA o AMPA como alternativa.",
            garantiaOportunidad: "Confirmación diagnóstica dentro de 45 días. Inicio de tratamiento desde confirmación.",
            tratamiento: "Cambios en estilo de vida (dieta DASH, ejercicio, restricción de sodio). Fármacos: IECA/ARA II, calcioantagonistas, tiazidas según perfil del paciente.",
            seguimiento: "Control mensual hasta alcanzar meta (< 140/90 mmHg, < 130/80 en diabéticos). Luego cada 3-6 meses. Evaluación anual de daño de órgano blanco."
        ),
        ProblemaGES(
            id: 22,
            nombre: "Epilepsia No Refractaria en Personas desde 1 Año y Menores de 15 Años",
            categoria: .neurologico,
            descripcion: "Crisis epilépticas recurrentes en edad pediátrica que responden adecuadamente al tratamiento farmacológico.",
            poblacionObjetivo: "Personas desde 1 año y menores de 15 años.",
            sospechaDiagnostica: "Crisis convulsivas recurrentes (≥ 2 crisis no provocadas), episodios de desconexión, automatismos, crisis tónico-clónicas generalizadas.",
            confirmacionDiagnostica: "Electroencefalograma (EEG). RNM de cerebro para descartar lesión estructural. Clasificación del tipo de epilepsia.",
            garantiaOportunidad: "Confirmación diagnóstica dentro de 60 días. Inicio de tratamiento desde confirmación.",
            tratamiento: "Antiepilépticos según tipo de crisis: ácido valproico (generalizada), carbamazepina u oxcarbazepina (focal). Monoterapia como primera línea.",
            seguimiento: "Control neurológico cada 3 meses el primer año, luego semestral. EEG de control. Niveles plasmáticos de antiepilépticos."
        ),
        ProblemaGES(
            id: 23,
            nombre: "Salud Oral Integral para Niños de 6 Años",
            categoria: .saludOral,
            descripcion: "Atención odontológica integral preventiva y recuperativa en niños de 6 años, edad clave para erupción del primer molar definitivo.",
            poblacionObjetivo: "Niños y niñas de 6 años.",
            sospechaDiagnostica: "Todo niño de 6 años. Evaluación de caries, anomalías dentomaxilares, gingivitis.",
            confirmacionDiagnostica: "Examen odontológico completo con radiografías bite-wing según necesidad.",
            garantiaOportunidad: "Alta odontológica integral dentro de 90 días desde la primera consulta.",
            tratamiento: "Sellantes de fisuras en primeros molares permanentes, obturaciones, exodoncias según necesidad, educación en higiene oral, aplicación de flúor.",
            seguimiento: "Control odontológico anual. Refuerzo de hábitos de higiene oral."
        ),
        ProblemaGES(
            id: 24,
            nombre: "Prevención del Parto Prematuro",
            categoria: .neonatalPediatrico,
            descripcion: "Prevención y manejo del parto prematuro. Incluye atención neonatal del prematuro y seguimiento del desarrollo.",
            poblacionObjetivo: "Embarazadas con riesgo de parto prematuro. Recién nacidos prematuros (< 37 semanas) y/o < 1500 g.",
            sospechaDiagnostica: "Contracciones uterinas antes de las 37 semanas, acortamiento cervical, rotura prematura de membranas, antecedente de parto prematuro previo.",
            confirmacionDiagnostica: "Cervicometría < 25 mm, test de fibronectina fetal, monitorización de dinámica uterina. Edad gestacional por FUR y/o ecografía.",
            garantiaOportunidad: "Atención inmediata ante amenaza de parto prematuro. Seguimiento del prematuro hasta los 7 años de edad corregida.",
            tratamiento: "Tocolisis, corticoides prenatales (betametasona), sulfato de magnesio como neuroprotector. Neonatal: surfactante, soporte ventilatorio, método canguro.",
            seguimiento: "Programa de seguimiento del prematuro: desarrollo psicomotor, screening auditivo y visual, evaluación neurológica periódica."
        ),
        ProblemaGES(
            id: 25,
            nombre: "Trastornos de Generación del Impulso y Conducción que Requieren Marcapaso",
            categoria: .cardiovascular,
            descripcion: "Bradiarritmias y trastornos de conducción cardíaca que requieren implante de marcapasos definitivo.",
            poblacionObjetivo: "Personas de 15 años y más.",
            sospechaDiagnostica: "Síncope, mareos, bradicardia sintomática (FC < 40 lpm), bloqueo AV completo, enfermedad del nodo sinusal.",
            confirmacionDiagnostica: "ECG con bradicardia o bloqueo AV. Holter de 24 horas. Estudio electrofisiológico en casos seleccionados.",
            garantiaOportunidad: "Confirmación dentro de 90 días. Implante de marcapasos dentro de 30 días desde indicación (urgente si sintomático).",
            tratamiento: "Implante de marcapasos definitivo (unicameral o bicameral según indicación). Marcapaso transitorio si urgencia.",
            seguimiento: "Control de marcapasos al mes, a los 6 meses y luego anual. Telemetría del dispositivo. Evaluación de umbral y batería."
        ),
        ProblemaGES(
            id: 26,
            nombre: "Colecistectomía Preventiva del Cáncer de Vesícula en Personas de 35 a 49 Años",
            categoria: .digestivo,
            descripcion: "Colecistectomía en personas sintomáticas con colelitiasis, como prevención del cáncer de vesícula biliar.",
            poblacionObjetivo: "Personas de 35 a 49 años sintomáticas con colelitiasis.",
            sospechaDiagnostica: "Dolor abdominal tipo cólico biliar (hipocondrio derecho postprandial), dispepsia, intolerancia a grasas.",
            confirmacionDiagnostica: "Ecografía abdominal que confirme colelitiasis. Laboratorio: perfil hepático.",
            garantiaOportunidad: "Confirmación diagnóstica dentro de 30 días. Colecistectomía dentro de 90 días desde indicación.",
            tratamiento: "Colecistectomía laparoscópica electiva. Conversión a cirugía abierta si complicaciones intraoperatorias.",
            seguimiento: "Control postoperatorio a los 7-10 días. Alta quirúrgica al mes. Estudio histopatológico de pieza operatoria (obligatorio)."
        ),
        ProblemaGES(
            id: 27,
            nombre: "Cáncer Gástrico",
            categoria: .oncologico,
            descripcion: "Neoplasia maligna del estómago. Chile tiene alta incidencia. Incluye diagnóstico, etapificación y tratamiento.",
            poblacionObjetivo: "Todas las personas de 15 años y más.",
            sospechaDiagnostica: "Epigastralgia persistente, baja de peso, anemia ferropénica, disfagia, saciedad precoz, hematemesis o melena.",
            confirmacionDiagnostica: "Endoscopía digestiva alta con biopsia. Etapificación con TAC tórax-abdomen-pelvis, endosonografía.",
            garantiaOportunidad: "Confirmación diagnóstica dentro de 30 días. Inicio de tratamiento dentro de 30 días post etapificación.",
            tratamiento: "Gastrectomía total o subtotal con linfadenectomía D2. Quimioterapia perioperatoria (FLOT) o adyuvante. Paliación en etapas avanzadas.",
            seguimiento: "Control cada 3 meses los primeros 2 años, semestral hasta 5 años. TAC y endoscopía según protocolo. Suplementación de vitamina B12."
        ),
        ProblemaGES(
            id: 28,
            nombre: "Cáncer de Próstata en Personas de 15 Años y Más",
            categoria: .oncologico,
            descripcion: "Neoplasia maligna de la glándula prostática. Cáncer más frecuente en hombres.",
            poblacionObjetivo: "Personas de 15 años y más con próstata.",
            sospechaDiagnostica: "PSA elevado (> 4 ng/mL), tacto rectal con nódulo o induración prostática, síntomas obstructivos urinarios.",
            confirmacionDiagnostica: "Biopsia prostática transrectal ecoguiada (12 cores). Clasificación de Gleason. Etapificación con RNM pélvica, cintigrama óseo.",
            garantiaOportunidad: "Confirmación diagnóstica dentro de 60 días. Tratamiento dentro de 60 días desde etapificación.",
            tratamiento: "Según etapa y riesgo: vigilancia activa, prostatectomía radical, radioterapia, hormonoterapia (análogos LHRH), quimioterapia.",
            seguimiento: "PSA cada 3 meses los primeros 2 años, semestral hasta 5 años. Meta: PSA indetectable post prostatectomía."
        ),
        ProblemaGES(
            id: 29,
            nombre: "Vicios de Refracción en Personas de 65 Años y Más",
            categoria: .oftalmologico,
            descripcion: "Corrección de errores refractivos (miopía, hipermetropía, astigmatismo, presbicia) mediante entrega de lentes ópticos.",
            poblacionObjetivo: "Personas de 65 años y más.",
            sospechaDiagnostica: "Disminución de agudeza visual, dificultad para leer, visión borrosa de lejos o cerca.",
            confirmacionDiagnostica: "Examen de agudeza visual y refracción por oftalmólogo u optómetra.",
            garantiaOportunidad: "Diagnóstico dentro de 180 días. Entrega de lentes dentro de 30 días desde prescripción.",
            tratamiento: "Prescripción y entrega de lentes ópticos correctores (lejos y/o cerca).",
            seguimiento: "Control anual de agudeza visual. Evaluación de patología ocular asociada."
        ),
        ProblemaGES(
            id: 30,
            nombre: "Estrabismo en Menores de 9 Años",
            categoria: .oftalmologico,
            descripcion: "Desviación del alineamiento ocular en la infancia. Requiere corrección para prevenir ambliopía.",
            poblacionObjetivo: "Menores de 9 años.",
            sospechaDiagnostica: "Desviación ocular visible, tortícolis, cierre de un ojo ante la luz, reflejo corneal asimétrico, test de Hirschberg positivo.",
            confirmacionDiagnostica: "Examen oftalmológico con cover test, refracción ciclopléjica, evaluación de motilidad ocular, fondo de ojo.",
            garantiaOportunidad: "Confirmación diagnóstica dentro de 90 días. Cirugía dentro de 180 días si está indicada.",
            tratamiento: "Corrección óptica, oclusión del ojo dominante (parche), cirugía de músculos extraoculares según tipo y magnitud.",
            seguimiento: "Control oftalmológico cada 3-6 meses hasta estabilización. Vigilancia de ambliopía."
        ),
        ProblemaGES(
            id: 31,
            nombre: "Retinopatía Diabética",
            categoria: .oftalmologico,
            descripcion: "Daño microvascular de la retina secundario a diabetes. Principal causa de ceguera prevenible en edad laboral.",
            poblacionObjetivo: "Personas con diabetes mellitus tipo 1 o tipo 2.",
            sospechaDiagnostica: "Paciente diabético con disminución de agudeza visual, manchas flotantes, o hallazgo en screening de fondo de ojo.",
            confirmacionDiagnostica: "Fondo de ojo con dilatación pupilar. Retinografía. Angiografía fluoresceínica y OCT en casos seleccionados.",
            garantiaOportunidad: "Confirmación dentro de 90 días. Tratamiento dentro de 60 días si retinopatía proliferativa o edema macular.",
            tratamiento: "Fotocoagulación láser (panretinal o focal). Anti-VEGF intravítreo en edema macular. Vitrectomía en hemorragia vítrea.",
            seguimiento: "Fondo de ojo anual en diabéticos sin retinopatía. Cada 3-6 meses si hay retinopatía. Control metabólico estricto."
        ),
        ProblemaGES(
            id: 32,
            nombre: "Desprendimiento de Retina Regmatógeno No Traumático",
            categoria: .oftalmologico,
            descripcion: "Separación de la retina neurosensorial del epitelio pigmentario por desgarro retinal.",
            poblacionObjetivo: "Todas las personas.",
            sospechaDiagnostica: "Fotopsias (destellos), miodesopsias súbitas (moscas volantes), defecto de campo visual progresivo (cortina oscura).",
            confirmacionDiagnostica: "Fondo de ojo con dilatación pupilar. Ecografía ocular si medios opacos.",
            garantiaOportunidad: "Confirmación y tratamiento dentro de 7 días desde sospecha (urgencia oftalmológica).",
            tratamiento: "Cirugía: vitrectomía posterior, retinopexia neumática o cirugía escleral (cerclaje/explante). Láser en desgarros sin desprendimiento.",
            seguimiento: "Control postoperatorio frecuente: día 1, semana 1, mes 1, luego mensual por 6 meses. Vigilancia del ojo contralateral."
        ),
        ProblemaGES(
            id: 33,
            nombre: "Hemofilia",
            categoria: .infeccioso,
            descripcion: "Trastorno hereditario de la coagulación por déficit de factor VIII (hemofilia A) o factor IX (hemofilia B).",
            poblacionObjetivo: "Todas las personas.",
            sospechaDiagnostica: "Sangrados desproporcionados a trauma, hematomas espontáneos, hemartrosis, sangrado prolongado post cirugía o extracción dental.",
            confirmacionDiagnostica: "TTPA prolongado con TP normal. Dosificación de factores VIII y IX. Estudio de inhibidores.",
            garantiaOportunidad: "Confirmación diagnóstica dentro de 30 días. Tratamiento inmediato de episodios hemorrágicos.",
            tratamiento: "Reposición de factor deficiente: concentrado de factor VIII o IX. Profilaxis primaria en hemofilia severa. Desmopresina en hemofilia A leve.",
            seguimiento: "Control hematológico cada 3-6 meses. Búsqueda periódica de inhibidores. Evaluación articular. Rehabilitación musculoesquelética."
        ),
        ProblemaGES(
            id: 34,
            nombre: "Depresión en Personas de 15 Años y Más",
            categoria: .saludMental,
            descripcion: "Trastorno depresivo mayor y distimia. Patología de salud mental de alta prevalencia en Chile.",
            poblacionObjetivo: "Personas de 15 años y más.",
            sospechaDiagnostica: "Ánimo depresivo, anhedonia, alteración del sueño y apetito, fatiga, dificultad de concentración, ideación suicida. ≥ 2 semanas de síntomas.",
            confirmacionDiagnostica: "Evaluación clínica según criterios CIE-10/DSM-5. Aplicación de escalas (PHQ-9, Beck). Descartar bipolaridad e hipotiroidismo.",
            garantiaOportunidad: "Confirmación diagnóstica dentro de 30 días. Inicio de tratamiento desde confirmación.",
            tratamiento: "Leve: psicoterapia. Moderada-severa: antidepresivos ISRS (fluoxetina, sertralina) + psicoterapia. Hospitalización si riesgo suicida alto.",
            seguimiento: "Control cada 2 semanas el primer mes, luego mensual. Mantener tratamiento 6-12 meses post remisión. Evaluación de riesgo suicida en cada control."
        ),
        ProblemaGES(
            id: 35,
            nombre: "Tratamiento de la Hiperplasia Benigna de la Próstata en Personas Sintomáticas",
            categoria: .renalUrologico,
            descripcion: "Crecimiento benigno de la próstata que causa síntomas urinarios obstructivos y/o irritativos.",
            poblacionObjetivo: "Personas sintomáticas con próstata.",
            sospechaDiagnostica: "Síntomas del tracto urinario inferior: chorro débil, goteo terminal, frecuencia, urgencia, nocturia. IPSS ≥ 8.",
            confirmacionDiagnostica: "Evaluación urológica, IPSS, uroflujometría, ecografía vesicoprostática con residuo postmiccional. PSA para descartar cáncer.",
            garantiaOportunidad: "Confirmación dentro de 180 días. Tratamiento médico inmediato, quirúrgico dentro de 365 días si indicado.",
            tratamiento: "Médico: alfa-bloqueadores (tamsulosina), inhibidores de 5-alfa-reductasa (finasteride). Quirúrgico: RTU prostática o adenomectomía.",
            seguimiento: "Control con IPSS y uroflujometría cada 6 meses. PSA anual. Evaluación de retención urinaria."
        ),
        ProblemaGES(
            id: 36,
            nombre: "Órtesis (o Ayudas Técnicas) para Personas de 65 Años y Más",
            categoria: .otros,
            descripcion: "Entrega de ayudas técnicas para mejorar la funcionalidad y autonomía de adultos mayores.",
            poblacionObjetivo: "Personas de 65 años y más con déficit funcional.",
            sospechaDiagnostica: "Dificultad para deambular, caídas recurrentes, dependencia en actividades de la vida diaria, necesidad de apoyo para movilidad.",
            confirmacionDiagnostica: "Evaluación funcional por médico o kinesiólogo. Identificación de ayuda técnica requerida.",
            garantiaOportunidad: "Evaluación dentro de 30 días. Entrega de ayuda técnica dentro de 90 días desde prescripción.",
            tratamiento: "Entrega de bastones, andadores, sillas de ruedas, colchón antiescaras, cojín antiescaras según necesidad evaluada.",
            seguimiento: "Control de uso y adaptación a la ayuda técnica. Evaluación de cambio o actualización según evolución."
        ),
        ProblemaGES(
            id: 37,
            nombre: "Accidente Cerebrovascular Isquémico en Personas de 15 Años y Más",
            categoria: .neurologico,
            descripcion: "Déficit neurológico focal agudo por isquemia cerebral. Emergencia médica tiempo-dependiente.",
            poblacionObjetivo: "Personas de 15 años y más.",
            sospechaDiagnostica: "Déficit neurológico focal súbito: hemiparesia, afasia, disartria, hemianopsia, ataxia. Escala NIHSS para gravedad.",
            confirmacionDiagnostica: "TAC de cerebro sin contraste (descartar hemorragia). AngioTAC si candidato a trombectomía. RNM con difusión.",
            garantiaOportunidad: "Evaluación e inicio de tratamiento inmediato. Trombolisis dentro de 4.5 horas desde inicio de síntomas.",
            tratamiento: "Trombolisis EV con alteplasa (ventana 4.5 horas). Trombectomía mecánica (ventana hasta 24 horas en seleccionados). Antiagregación, estatinas.",
            seguimiento: "Rehabilitación precoz (kinesiología, fonoaudiología, terapia ocupacional). Control factores de riesgo. Prevención secundaria."
        ),
        ProblemaGES(
            id: 38,
            nombre: "Enfermedad Pulmonar Obstructiva Crónica de Tratamiento Ambulatorio",
            categoria: .respiratorio,
            descripcion: "Enfermedad respiratoria crónica con obstrucción no completamente reversible del flujo aéreo.",
            poblacionObjetivo: "Todas las personas.",
            sospechaDiagnostica: "Disnea progresiva, tos crónica productiva, exposición a tabaco o contaminantes. Paciente > 40 años fumador.",
            confirmacionDiagnostica: "Espirometría con VEF1/CVF < 0.7 post broncodilatador. Clasificación GOLD según VEF1.",
            garantiaOportunidad: "Confirmación diagnóstica dentro de 60 días. Tratamiento desde confirmación.",
            tratamiento: "Cesación tabáquica. Broncodilatadores inhalados (LABA, LAMA). Corticoides inhalados si exacerbaciones frecuentes. Rehabilitación pulmonar.",
            seguimiento: "Espirometría anual. Vacunación influenza y neumococo. Evaluación de exacerbaciones. Oxigenoterapia si PaO2 < 55 mmHg."
        ),
        ProblemaGES(
            id: 39,
            nombre: "Asma Bronquial Moderada y Grave en Menores de 15 Años",
            categoria: .respiratorio,
            descripcion: "Enfermedad inflamatoria crónica de la vía aérea con hiperreactividad bronquial en niños.",
            poblacionObjetivo: "Menores de 15 años con asma moderada o grave.",
            sospechaDiagnostica: "Sibilancias recurrentes, tos nocturna, disnea con ejercicio, antecedentes de atopia. Síntomas > 2 veces por semana.",
            confirmacionDiagnostica: "Espirometría con prueba de reversibilidad (> 12% y > 200 mL). En menores de 5 años: diagnóstico clínico.",
            garantiaOportunidad: "Confirmación dentro de 60 días. Inicio de tratamiento desde confirmación.",
            tratamiento: "Corticoides inhalados (budesonida, fluticasona) como controlador. LABA si no se controla. Salbutamol como rescate. Plan de acción escrito.",
            seguimiento: "Control cada 1-3 meses según nivel de control. Espirometría semestral. Evaluación de técnica inhalatoria. Educación."
        ),
        ProblemaGES(
            id: 40,
            nombre: "Síndrome de Dificultad Respiratoria en el Recién Nacido",
            categoria: .neonatalPediatrico,
            descripcion: "Insuficiencia respiratoria neonatal por déficit de surfactante u otras causas. Emergencia neonatal.",
            poblacionObjetivo: "Recién nacidos.",
            sospechaDiagnostica: "Dificultad respiratoria desde las primeras horas: taquipnea, retracción costal, quejido espiratorio, cianosis. Test de Silverman > 3.",
            confirmacionDiagnostica: "Radiografía de tórax (patrón reticulogranular difuso en enfermedad de membrana hialina). Gases arteriales.",
            garantiaOportunidad: "Atención inmediata. Tratamiento con surfactante dentro de las primeras 2 horas de vida.",
            tratamiento: "Surfactante exógeno endotraqueal. Soporte ventilatorio (CPAP, ventilación mecánica). Oxigenoterapia controlada.",
            seguimiento: "Monitorización en UCI neonatal. Evaluación de displasia broncopulmonar. Seguimiento del prematuro si corresponde."
        ),
        ProblemaGES(
            id: 41,
            nombre: "Tratamiento Médico en Personas de 55 Años y Más con Artrosis de Cadera y/o Rodilla",
            categoria: .musculoesqueletico,
            descripcion: "Manejo conservador de artrosis leve a moderada de cadera y/o rodilla en adultos mayores.",
            poblacionObjetivo: "Personas de 55 años y más con artrosis de cadera y/o rodilla leve o moderada.",
            sospechaDiagnostica: "Dolor articular mecánico (aumenta con actividad, mejora con reposo), rigidez matinal < 30 minutos, crepitación articular.",
            confirmacionDiagnostica: "Radiografía de articulación afectada. Criterios ACR para artrosis. Clasificación Kellgren-Lawrence grado 1-2.",
            garantiaOportunidad: "Confirmación dentro de 120 días. Inicio de tratamiento desde confirmación.",
            tratamiento: "Educación, baja de peso, ejercicio terapéutico, kinesioterapia. Paracetamol, AINES en agudizaciones. Infiltraciones intraarticulares.",
            seguimiento: "Control cada 3-6 meses. Evaluación de progresión radiológica. Derivar a cirugía si artrosis severa."
        ),
        ProblemaGES(
            id: 42,
            nombre: "Hemorragia Subaracnoidea Secundaria a Ruptura de Aneurismas Cerebrales",
            categoria: .neurologico,
            descripcion: "Sangrado en el espacio subaracnoideo por ruptura de aneurisma cerebral. Emergencia neuroquirúrgica.",
            poblacionObjetivo: "Todas las personas de 15 años y más.",
            sospechaDiagnostica: "Cefalea súbita e intensa ('la peor de mi vida'), rigidez de nuca, vómitos, alteración de conciencia, déficit neurológico focal.",
            confirmacionDiagnostica: "TAC de cerebro sin contraste (hiperdensidad en cisternas basales). Si TAC normal: punción lumbar. AngioTAC o angiografía cerebral.",
            garantiaOportunidad: "Tratamiento neuroquirúrgico dentro de las primeras 24 horas desde confirmación.",
            tratamiento: "Clipaje quirúrgico o embolización endovascular del aneurisma. Manejo en UCI: nimodipino, control de PA, prevención de vasoespasmo.",
            seguimiento: "Rehabilitación neurológica. AngioTAC de control. Vigilancia de vasoespasmo hasta día 14. Screening familiar de aneurismas."
        ),
        ProblemaGES(
            id: 43,
            nombre: "Tumores Primarios del Sistema Nervioso Central en Personas de 15 Años y Más",
            categoria: .oncologico,
            descripcion: "Neoplasias primarias intracraneales e intrarraquídeas. Incluye gliomas, meningiomas y otros.",
            poblacionObjetivo: "Personas de 15 años y más.",
            sospechaDiagnostica: "Cefalea progresiva con signos de hipertensión endocraneana, déficit neurológico focal progresivo, crisis epilépticas de inicio tardío.",
            confirmacionDiagnostica: "RNM de cerebro con gadolinio. Biopsia estereotáxica o resección quirúrgica con estudio histopatológico.",
            garantiaOportunidad: "Confirmación dentro de 30 días. Inicio de tratamiento dentro de 30 días desde confirmación.",
            tratamiento: "Cirugía (resección máxima segura). Radioterapia y temozolomida en gliomas de alto grado. Observación en meningiomas grado I.",
            seguimiento: "RNM de control cada 3 meses el primer año, luego semestral. Evaluación neurológica y funcional periódica."
        ),
        ProblemaGES(
            id: 44,
            nombre: "Tratamiento Quirúrgico de Hernia del Núcleo Pulposo Lumbar",
            categoria: .musculoesqueletico,
            descripcion: "Hernia discal lumbar con compresión radicular que requiere resolución quirúrgica.",
            poblacionObjetivo: "Personas de 15 años y más con indicación quirúrgica.",
            sospechaDiagnostica: "Lumbociática con déficit neurológico (paresia, hipoestesia, arreflexia), Lasègue positivo, síndrome de cauda equina.",
            confirmacionDiagnostica: "RNM de columna lumbar que muestra hernia discal concordante con clínica. EMG en casos dudosos.",
            garantiaOportunidad: "Confirmación dentro de 60 días. Cirugía dentro de 90 días desde indicación (urgente en cauda equina).",
            tratamiento: "Discectomía lumbar (microdiscectomía). Cirugía de urgencia en síndrome de cauda equina (< 48 horas).",
            seguimiento: "Control postoperatorio a las 2 semanas y al mes. Rehabilitación kinésica. Reintegro laboral progresivo."
        ),
        ProblemaGES(
            id: 45,
            nombre: "Leucemia en Personas de 15 Años y Más",
            categoria: .oncologico,
            descripcion: "Neoplasia hematológica maligna. Incluye leucemias agudas (LLA, LMA) y leucemia mieloide crónica.",
            poblacionObjetivo: "Personas de 15 años y más.",
            sospechaDiagnostica: "Palidez, fatiga, fiebre, infecciones recurrentes, sangrado mucocutáneo, adenopatías, esplenomegalia, dolor óseo.",
            confirmacionDiagnostica: "Hemograma con blastos, mielograma con > 20% blastos, inmunofenotipo, citogenética, biología molecular.",
            garantiaOportunidad: "Confirmación dentro de 14 días. Inicio de tratamiento dentro de 14 días desde confirmación.",
            tratamiento: "LLA: quimioterapia de inducción, consolidación, mantención. LMA: quimioterapia intensiva. LMC: imatinib. Trasplante de médula en seleccionados.",
            seguimiento: "Control hematológico según protocolo. Evaluación de remisión completa. Vigilancia de recaída y efectos secundarios."
        ),
        ProblemaGES(
            id: 46,
            nombre: "Urgencia Odontológica Ambulatoria",
            categoria: .saludOral,
            descripcion: "Atención de emergencias dentales que causan dolor agudo, infección o trauma dentoalveolar.",
            poblacionObjetivo: "Todas las personas.",
            sospechaDiagnostica: "Dolor dental agudo, absceso dentario, trauma dentoalveolar (fractura o avulsión dentaria), complicación post exodoncia.",
            confirmacionDiagnostica: "Examen odontológico. Radiografía periapical según necesidad.",
            garantiaOportunidad: "Atención dentro de 24 horas desde la solicitud.",
            tratamiento: "Drenaje de absceso, pulpotomía, reimplante dentario en avulsión, exodoncia de urgencia, sutura de tejidos blandos, analgesia.",
            seguimiento: "Control a las 24-48 horas si procedimiento invasivo. Derivación a atención odontológica integral."
        ),
        ProblemaGES(
            id: 47,
            nombre: "Salud Oral Integral del Adulto de 60 Años",
            categoria: .saludOral,
            descripcion: "Atención odontológica integral para adultos de 60 años, incluyendo rehabilitación protésica.",
            poblacionObjetivo: "Personas de 60 años.",
            sospechaDiagnostica: "Todo adulto de 60 años. Evaluación de caries, enfermedad periodontal, edentulismo, necesidad protésica.",
            confirmacionDiagnostica: "Examen odontológico integral con radiografías según necesidad.",
            garantiaOportunidad: "Alta integral dentro de 120 días desde primera consulta.",
            tratamiento: "Obturaciones, exodoncias, tratamiento periodontal, prótesis dental removible (parcial o total) según necesidad.",
            seguimiento: "Control de adaptación protésica a los 7, 15 y 30 días. Control odontológico anual."
        ),
        ProblemaGES(
            id: 48,
            nombre: "Politraumatizado Grave",
            categoria: .traumatismoUrgencias,
            descripcion: "Paciente con lesiones traumáticas múltiples con riesgo vital. Requiere manejo en centro de trauma.",
            poblacionObjetivo: "Todas las personas.",
            sospechaDiagnostica: "Trauma de alta energía con compromiso de dos o más sistemas. ISS > 15. Inestabilidad hemodinámica, compromiso de conciencia.",
            confirmacionDiagnostica: "Evaluación primaria ABCDE. TAC de cuerpo completo (pan-scan). FAST ecográfico. Laboratorio de urgencia.",
            garantiaOportunidad: "Atención inmediata. Estabilización y tratamiento definitivo en centro de trauma.",
            tratamiento: "Reanimación con control de daños. Cirugía de control de daños. Manejo en UCI. Cirugía definitiva diferida.",
            seguimiento: "Rehabilitación integral. Evaluación de secuelas. Apoyo psicológico. Reinserción laboral y social."
        ),
        ProblemaGES(
            id: 49,
            nombre: "Traumatismo Cráneo Encefálico Moderado o Grave",
            categoria: .traumatismoUrgencias,
            descripcion: "Trauma craneal con GCS ≤ 12 que requiere manejo neuroquirúrgico y en UCI.",
            poblacionObjetivo: "Todas las personas.",
            sospechaDiagnostica: "Trauma craneal con GCS 9-12 (moderado) o GCS ≤ 8 (grave). Pérdida de conciencia, déficit neurológico, convulsiones post trauma.",
            confirmacionDiagnostica: "TAC de cerebro sin contraste urgente. Evaluación neuroquirúrgica.",
            garantiaOportunidad: "TAC dentro de 1 hora. Neurocirugía de urgencia si lesión operable.",
            tratamiento: "Manejo en UCI: neuroprotección, control de PIC, cirugía descompresiva o evacuación de hematomas. Prevención de daño secundario.",
            seguimiento: "Rehabilitación neurológica integral. Evaluación neuropsicológica. Seguimiento de epilepsia postraumática."
        ),
        ProblemaGES(
            id: 50,
            nombre: "Trauma Ocular Grave",
            categoria: .traumatismoUrgencias,
            descripcion: "Lesión traumática ocular con riesgo de pérdida visual. Incluye trauma abierto y cerrado del globo ocular.",
            poblacionObjetivo: "Todas las personas.",
            sospechaDiagnostica: "Trauma ocular directo, disminución de agudeza visual post trauma, ojo rojo, dolor ocular intenso, hifema, herida corneoescleral.",
            confirmacionDiagnostica: "Examen oftalmológico de urgencia. Evaluación con lámpara de hendidura. TAC de órbita si sospecha de cuerpo extraño intraocular.",
            garantiaOportunidad: "Atención oftalmológica dentro de 48 horas. Cirugía de urgencia si globo abierto.",
            tratamiento: "Reparación quirúrgica de globo abierto (< 24 horas). Manejo de hifema, desprendimiento de retina traumático, catarata traumática.",
            seguimiento: "Control oftalmológico frecuente post trauma. Vigilancia de glaucoma secundario, desprendimiento de retina tardío."
        ),
        ProblemaGES(
            id: 51,
            nombre: "Fibrosis Quística",
            categoria: .respiratorio,
            descripcion: "Enfermedad genética autosómica recesiva que afecta pulmones, páncreas y otros órganos por disfunción del canal CFTR.",
            poblacionObjetivo: "Todas las personas.",
            sospechaDiagnostica: "Infecciones respiratorias recurrentes, bronquiectasias, insuficiencia pancreática, íleo meconial, falla de medro, sudor salado.",
            confirmacionDiagnostica: "Test del sudor (cloro > 60 mmol/L positivo). Estudio genético de mutaciones CFTR. Screening neonatal (TIR).",
            garantiaOportunidad: "Confirmación dentro de 30 días. Tratamiento desde confirmación.",
            tratamiento: "Kinesioterapia respiratoria diaria, antibióticos (tobramicina inhalada), enzimas pancreáticas, vitaminas liposolubles, DNasa. Moduladores CFTR en elegibles.",
            seguimiento: "Control multidisciplinario cada 1-3 meses. Cultivos de esputo, espirometría, evaluación nutricional. Referir a trasplante pulmonar si indicado."
        ),
        ProblemaGES(
            id: 52,
            nombre: "Artritis Reumatoide",
            categoria: .musculoesqueletico,
            descripcion: "Enfermedad autoinmune inflamatoria crónica que afecta articulaciones sinoviales, principalmente de manos y pies.",
            poblacionObjetivo: "Personas de 15 años y más.",
            sospechaDiagnostica: "Poliartritis simétrica de pequeñas articulaciones (MCF, IFP), rigidez matinal > 1 hora, artralgia con inflamación > 6 semanas.",
            confirmacionDiagnostica: "Criterios ACR/EULAR 2010. Factor reumatoide, anti-CCP. PCR, VHS. Radiografía de manos y pies.",
            garantiaOportunidad: "Confirmación dentro de 90 días. Inicio de FARME dentro de 30 días desde confirmación.",
            tratamiento: "Metotrexato como primera línea. Asociar leflunomida, sulfasalazina si insuficiente. Biológicos (anti-TNF) si falla a FARMEs convencionales.",
            seguimiento: "Control cada 1-3 meses hasta remisión. DAS28 para evaluar actividad. Monitoreo hepático y hematológico con metotrexato."
        ),
        ProblemaGES(
            id: 53,
            nombre: "Consumo Perjudicial o Dependencia de Alcohol y Drogas en Menores de 20 Años",
            categoria: .saludMental,
            descripcion: "Consumo problemático de sustancias en adolescentes y jóvenes. Incluye intervención y rehabilitación.",
            poblacionObjetivo: "Menores de 20 años con consumo perjudicial o dependencia de riesgo bajo a moderado.",
            sospechaDiagnostica: "Consumo recurrente con consecuencias negativas (académicas, familiares, legales), cambios conductuales, deterioro funcional.",
            confirmacionDiagnostica: "Evaluación clínica con instrumentos validados (CRAFFT, AUDIT). Diagnóstico según CIE-10.",
            garantiaOportunidad: "Confirmación dentro de 30 días. Inicio de tratamiento dentro de 10 días desde confirmación.",
            tratamiento: "Intervención breve, psicoterapia individual y familiar, tratamiento ambulatorio intensivo. Desintoxicación si necesario.",
            seguimiento: "Seguimiento por al menos 12 meses. Prevención de recaídas. Reinserción escolar y social."
        ),
        ProblemaGES(
            id: 54,
            nombre: "Analgesia del Parto",
            categoria: .otros,
            descripcion: "Derecho a analgesia durante el trabajo de parto, principalmente mediante analgesia epidural.",
            poblacionObjetivo: "Mujeres en trabajo de parto.",
            sospechaDiagnostica: "Toda mujer en trabajo de parto que solicite analgesia, con dilatación cervical adecuada (≥ 4-5 cm generalmente).",
            confirmacionDiagnostica: "Evaluación obstétrica y anestésica. Verificar ausencia de contraindicaciones para analgesia regional.",
            garantiaOportunidad: "Administración de analgesia dentro de 60 minutos desde la solicitud.",
            tratamiento: "Analgesia epidural o combinada espinal-epidural. Alternativas: óxido nitroso, opioides parenterales si contraindicación.",
            seguimiento: "Monitorización continua durante analgesia. Evaluación de bloqueo motor. Control de signos vitales maternos y fetales."
        ),
        ProblemaGES(
            id: 55,
            nombre: "Gran Quemado",
            categoria: .traumatismoUrgencias,
            descripcion: "Quemaduras extensas o profundas que requieren manejo en unidad especializada de quemados.",
            poblacionObjetivo: "Todas las personas.",
            sospechaDiagnostica: "Quemaduras > 20% SCQ en adultos, > 10% en niños, quemaduras de vía aérea, quemaduras eléctricas, quemaduras profundas en áreas especiales.",
            confirmacionDiagnostica: "Evaluación de extensión (regla de los 9 o Lund-Browder), profundidad y localización. Clasificación como gran quemado.",
            garantiaOportunidad: "Atención inmediata. Traslado a centro de quemados dentro de las primeras 24 horas.",
            tratamiento: "Reanimación con fluidos (fórmula de Parkland), manejo de vía aérea, escarotomía, aseo quirúrgico, injertos cutáneos, rehabilitación.",
            seguimiento: "Rehabilitación prolongada. Uso de prendas compresivas. Cirugía reconstructiva de secuelas. Apoyo psicológico."
        ),
        ProblemaGES(
            id: 56,
            nombre: "Hipoacusia Bilateral en Personas de 65 Años y Más que Requieren Uso de Audífono",
            categoria: .otros,
            descripcion: "Pérdida auditiva bilateral en adultos mayores con indicación de uso de audífono.",
            poblacionObjetivo: "Personas de 65 años y más con hipoacusia bilateral.",
            sospechaDiagnostica: "Dificultad para escuchar conversaciones, necesidad de subir volumen de TV, aislamiento social por hipoacusia.",
            confirmacionDiagnostica: "Audiometría tonal que muestre hipoacusia bilateral ≥ 40 dB en promedio de frecuencias conversacionales.",
            garantiaOportunidad: "Confirmación dentro de 120 días. Entrega de audífono dentro de 45 días desde prescripción.",
            tratamiento: "Adaptación de audífono (uno o bilateral según indicación). Rehabilitación auditiva.",
            seguimiento: "Control de adaptación al audífono a las 2 semanas, al mes y a los 3 meses. Control audiométrico anual."
        ),
        ProblemaGES(
            id: 57,
            nombre: "Retinopatía del Prematuro",
            categoria: .neonatalPediatrico,
            descripcion: "Enfermedad vasoproliferativa de la retina en prematuros que puede causar desprendimiento de retina y ceguera.",
            poblacionObjetivo: "Recién nacidos prematuros < 32 semanas o < 1500 g de peso al nacer.",
            sospechaDiagnostica: "Todo prematuro < 32 semanas o < 1500 g. Screening obligatorio con fondo de ojo.",
            confirmacionDiagnostica: "Fondo de ojo con oftalmoscopio indirecto binocular por oftalmólogo entrenado. Clasificación ICROP.",
            garantiaOportunidad: "Primer fondo de ojo entre las 4-6 semanas de vida. Tratamiento dentro de 72 horas si indicado.",
            tratamiento: "Láser transpupilar o crioterapia en estadios con indicación (enfermedad umbral). Anti-VEGF en casos seleccionados. Vitrectomía en estadio 4-5.",
            seguimiento: "Fondo de ojo seriado cada 1-2 semanas hasta vascularización retinal completa. Seguimiento oftalmológico a largo plazo."
        ),
        ProblemaGES(
            id: 58,
            nombre: "Displasia Broncopulmonar del Prematuro",
            categoria: .neonatalPediatrico,
            descripcion: "Enfermedad pulmonar crónica del prematuro que requiere oxígeno suplementario a las 36 semanas de edad corregida.",
            poblacionObjetivo: "Recién nacidos prematuros con displasia broncopulmonar.",
            sospechaDiagnostica: "Prematuro con necesidad persistente de oxígeno suplementario a las 36 semanas de edad gestacional corregida.",
            confirmacionDiagnostica: "Necesidad de O2 suplementario a las 36 semanas de edad corregida. Radiografía de tórax con patrón compatible.",
            garantiaOportunidad: "Diagnóstico y tratamiento inmediato. Seguimiento en programa de oxígeno domiciliario.",
            tratamiento: "Oxigenoterapia domiciliaria, broncodilatadores inhalados, diuréticos, corticoides en exacerbaciones. Vacuna anti-VRS (palivizumab).",
            seguimiento: "Control mensual con saturometría. Retiro gradual de oxígeno. Evaluación de función pulmonar. Seguimiento hasta los 7 años."
        ),
        ProblemaGES(
            id: 59,
            nombre: "Hipoacusia Neurosensorial Bilateral del Prematuro",
            categoria: .neonatalPediatrico,
            descripcion: "Pérdida auditiva neurosensorial bilateral en prematuros. Detección e intervención precoz son críticas para el desarrollo del lenguaje.",
            poblacionObjetivo: "Recién nacidos prematuros < 32 semanas o < 1500 g con hipoacusia neurosensorial bilateral.",
            sospechaDiagnostica: "Screening auditivo neonatal alterado (emisiones otoacústicas o potenciales evocados), prematuro con factores de riesgo (hiperbilirrubinemia, aminoglicósidos, asfixia).",
            confirmacionDiagnostica: "Potenciales evocados auditivos de tronco cerebral (BERA/ABR). Emisiones otoacústicas. Impedanciometría.",
            garantiaOportunidad: "Screening auditivo antes del alta neonatal. Confirmación dentro de 3 meses de edad corregida. Intervención antes de los 6 meses.",
            tratamiento: "Implementación de audífonos bilaterales. Terapia auditivo-verbal precoz. Implante coclear si hipoacusia severa-profunda bilateral sin beneficio con audífonos.",
            seguimiento: "Control audiológico cada 3 meses. Evaluación del desarrollo del lenguaje. Ajuste de audífonos según crecimiento y evolución audiométrica."
        ),
        ProblemaGES(
            id: 60,
            nombre: "Epilepsia No Refractaria en Personas de 15 Años y Más",
            categoria: .neurologico,
            descripcion: "Epilepsia en adultos que responde al tratamiento farmacológico con antiepilépticos.",
            poblacionObjetivo: "Personas de 15 años y más.",
            sospechaDiagnostica: "Crisis epilépticas recurrentes (≥ 2 crisis no provocadas), pérdida de conciencia, movimientos tónico-clónicos, automatismos, aura.",
            confirmacionDiagnostica: "EEG (puede ser normal interictalmente). RNM de cerebro. Clasificación del tipo de epilepsia y crisis.",
            garantiaOportunidad: "Confirmación dentro de 60 días. Inicio de tratamiento desde confirmación.",
            tratamiento: "Monoterapia inicial: levetiracetam, lamotrigina (focal), ácido valproico (generalizada). Ajustar según respuesta y tolerancia.",
            seguimiento: "Control neurológico cada 3-6 meses. EEG de control. Educación sobre restricciones (conducción, natación). Considerar retiro tras 2 años sin crisis."
        ),
        ProblemaGES(
            id: 61,
            nombre: "Asma Bronquial en Personas de 15 Años y Más",
            categoria: .respiratorio,
            descripcion: "Enfermedad inflamatoria crónica de la vía aérea con obstrucción reversible del flujo aéreo en adultos.",
            poblacionObjetivo: "Personas de 15 años y más.",
            sospechaDiagnostica: "Sibilancias recurrentes, disnea episódica, tos nocturna o con ejercicio, opresión torácica. Mejora con broncodilatadores.",
            confirmacionDiagnostica: "Espirometría con prueba broncodilatadora positiva (aumento VEF1 ≥ 12% y ≥ 200 mL). Test de metacolina si espirometría normal.",
            garantiaOportunidad: "Confirmación dentro de 60 días. Tratamiento desde confirmación.",
            tratamiento: "Escalones GINA: ICS dosis baja + formoterol PRN. Escalar: ICS dosis media + LABA. ICS dosis alta + LABA. Biológicos en asma grave.",
            seguimiento: "Control cada 1-3 meses hasta lograr control. Evaluación de técnica inhalatoria, adherencia, control ambiental. Espirometría anual."
        ),
        ProblemaGES(
            id: 62,
            nombre: "Enfermedad de Parkinson",
            categoria: .neurologico,
            descripcion: "Enfermedad neurodegenerativa progresiva con pérdida de neuronas dopaminérgicas en sustancia nigra.",
            poblacionObjetivo: "Todas las personas.",
            sospechaDiagnostica: "Temblor de reposo unilateral, bradicinesia, rigidez, inestabilidad postural. Inicio asimétrico. Buena respuesta a levodopa.",
            confirmacionDiagnostica: "Diagnóstico clínico según criterios UK Brain Bank. RNM para descartar causas secundarias. DATScan en casos dudosos.",
            garantiaOportunidad: "Confirmación dentro de 90 días. Inicio de tratamiento desde confirmación.",
            tratamiento: "Levodopa/carbidopa (gold standard). Agonistas dopaminérgicos (pramipexol, rotigotina). Inhibidores MAO-B, COMT. Rehabilitación motora.",
            seguimiento: "Control neurológico cada 3-6 meses. Ajuste de dosis según progresión y complicaciones motoras (fluctuaciones, discinesias)."
        ),
        ProblemaGES(
            id: 63,
            nombre: "Artritis Idiopática Juvenil",
            categoria: .musculoesqueletico,
            descripcion: "Artritis crónica de causa desconocida que se inicia antes de los 16 años y persiste por más de 6 semanas.",
            poblacionObjetivo: "Personas menores de 16 años.",
            sospechaDiagnostica: "Artritis (tumefacción articular o limitación de rango con dolor) de más de 6 semanas en menores de 16 años. Rigidez matinal.",
            confirmacionDiagnostica: "Diagnóstico clínico de exclusión. Laboratorio: VHS, PCR, FR, ANA, HLA-B27. Radiografía y ecografía articular.",
            garantiaOportunidad: "Confirmación dentro de 90 días. Inicio de tratamiento dentro de 30 días.",
            tratamiento: "AINES como primera línea. Metotrexato si poliarticular o refractaria. Biológicos (etanercept, adalimumab) si falla a FARMEs. Corticoides intraarticulares.",
            seguimiento: "Control reumatológico cada 1-3 meses. Evaluación oftalmológica cada 3-6 meses (uveítis). Monitoreo de crecimiento."
        ),
        ProblemaGES(
            id: 64,
            nombre: "Prevención Secundaria de la Insuficiencia Renal Crónica Terminal",
            categoria: .renalUrologico,
            descripcion: "Manejo de enfermedad renal crónica etapas 3-4 para retrasar progresión a diálisis.",
            poblacionObjetivo: "Personas con enfermedad renal crónica etapas 3b y 4 (VFG 15-44 mL/min).",
            sospechaDiagnostica: "VFG disminuida en pacientes con factores de riesgo: diabetes, hipertensión, proteinuria persistente.",
            confirmacionDiagnostica: "VFG estimada (CKD-EPI) entre 15-44 mL/min confirmada en 2 mediciones separadas por 3 meses. Proteinuria.",
            garantiaOportunidad: "Evaluación por nefrólogo dentro de 90 días. Inicio de plan de manejo desde confirmación.",
            tratamiento: "Control estricto de PA (< 130/80), IECA/ARA II, control glicémico en diabéticos, restricción proteica, manejo de dislipidemia, evitar nefrotóxicos.",
            seguimiento: "Control nefrológico cada 3-6 meses. Monitoreo de VFG, proteinuria, electrolitos, hemoglobina, metabolismo óseo-mineral. Preparación para TRR."
        ),
        ProblemaGES(
            id: 65,
            nombre: "Displasia Luxante de Caderas",
            categoria: .neonatalPediatrico,
            descripcion: "Alteración del desarrollo de la articulación coxofemoral en lactantes. Detección y tratamiento precoz evitan secuelas.",
            poblacionObjetivo: "Recién nacidos y lactantes.",
            sospechaDiagnostica: "Barlow y Ortolani positivos, asimetría de pliegues, limitación de abducción de caderas, acortamiento de extremidad.",
            confirmacionDiagnostica: "Ecografía de caderas (< 3 meses). Radiografía de pelvis AP a partir de los 3 meses. Clasificación de Graf.",
            garantiaOportunidad: "Confirmación dentro de 60 días desde sospecha. Tratamiento inmediato desde confirmación.",
            tratamiento: "Arnés de Pavlik en menores de 6 meses. Reducción cerrada o abierta en casos tardíos o refractarios. Yeso pelvipédico.",
            seguimiento: "Ecografía o radiografía de control según tratamiento. Seguimiento ortopédico hasta madurez esquelética."
        ),
        ProblemaGES(
            id: 66,
            nombre: "Salud Oral Integral de la Embarazada",
            categoria: .saludOral,
            descripcion: "Atención odontológica integral durante el embarazo para prevenir y tratar patología oral.",
            poblacionObjetivo: "Mujeres embarazadas.",
            sospechaDiagnostica: "Toda mujer embarazada. Mayor riesgo de gingivitis gravídica, caries por cambios dietéticos y de pH salival.",
            confirmacionDiagnostica: "Examen odontológico integral con anamnesis obstétrica.",
            garantiaOportunidad: "Alta odontológica integral antes del parto.",
            tratamiento: "Educación en higiene oral, destartraje, obturaciones, exodoncias según necesidad, tratamiento de gingivitis. Procedimientos seguros en 2do trimestre.",
            seguimiento: "Control odontológico durante el embarazo. Refuerzo de higiene oral."
        ),
        ProblemaGES(
            id: 67,
            nombre: "Esclerosis Múltiple Remitente Recurrente",
            categoria: .neurologico,
            descripcion: "Enfermedad desmielinizante autoinmune del SNC con brotes y remisiones.",
            poblacionObjetivo: "Personas de 15 años y más con forma remitente recurrente.",
            sospechaDiagnostica: "Déficit neurológico focal (neuritis óptica, mielitis, déficit sensitivo-motor) con remisión, en adulto joven (20-40 años).",
            confirmacionDiagnostica: "Criterios de McDonald: RNM con lesiones desmielinizantes diseminadas en tiempo y espacio. Bandas oligoclonales en LCR.",
            garantiaOportunidad: "Confirmación dentro de 60 días. Inicio de tratamiento desde confirmación.",
            tratamiento: "Brotes: metilprednisolona EV. Terapia modificadora: interferón beta, acetato de glatiramer, fingolimod, natalizumab según actividad.",
            seguimiento: "Control neurológico cada 3-6 meses. RNM anual. Evaluación de discapacidad (EDSS). Monitoreo de efectos adversos de terapia."
        ),
        ProblemaGES(
            id: 68,
            nombre: "Hepatitis B Crónica",
            categoria: .infeccioso,
            descripcion: "Infección crónica por virus hepatitis B con riesgo de cirrosis y hepatocarcinoma.",
            poblacionObjetivo: "Todas las personas.",
            sospechaDiagnostica: "Ictericia, elevación de transaminasas, factores de riesgo (contacto con portadores, uso de drogas EV, conducta sexual de riesgo).",
            confirmacionDiagnostica: "HBsAg positivo por más de 6 meses. HBeAg, anti-HBe, carga viral VHB, perfil hepático completo.",
            garantiaOportunidad: "Confirmación dentro de 45 días. Inicio de tratamiento desde confirmación si indicado.",
            tratamiento: "Antivirales (tenofovir, entecavir) en hepatitis crónica activa. Interferón pegilado en seleccionados.",
            seguimiento: "Control cada 3-6 meses con carga viral, HBeAg, perfil hepático. Screening de hepatocarcinoma cada 6 meses (ecografía + AFP)."
        ),
        ProblemaGES(
            id: 69,
            nombre: "Hepatitis C Crónica",
            categoria: .infeccioso,
            descripcion: "Infección crónica por virus hepatitis C. Actualmente curable con antivirales de acción directa.",
            poblacionObjetivo: "Todas las personas.",
            sospechaDiagnostica: "Generalmente asintomática. Elevación de transaminasas, factores de riesgo (transfusión antes de 1996, uso drogas EV, tatuajes, hemodiálisis).",
            confirmacionDiagnostica: "Anti-VHC positivo confirmado con carga viral VHC (RNA). Genotipificación. Evaluación de fibrosis (FibroScan o biopsia).",
            garantiaOportunidad: "Confirmación dentro de 45 días. Inicio de tratamiento dentro de 30 días desde indicación.",
            tratamiento: "Antivirales de acción directa (DAA): sofosbuvir/velpatasvir pangenotípico por 12 semanas. Tasa de curación > 95%.",
            seguimiento: "Carga viral a las 12 semanas post tratamiento (RVS12 = curación). Screening de hepatocarcinoma si cirrosis."
        ),
        ProblemaGES(
            id: 70,
            nombre: "Cáncer Colorrectal en Personas de 15 Años y Más",
            categoria: .oncologico,
            descripcion: "Neoplasia maligna de colon y recto. Tercera causa de muerte por cáncer.",
            poblacionObjetivo: "Personas de 15 años y más.",
            sospechaDiagnostica: "Cambio del hábito intestinal, rectorragia, anemia ferropénica inexplicada, baja de peso, masa abdominal palpable, test de sangre oculta positivo.",
            confirmacionDiagnostica: "Colonoscopía con biopsia. Etapificación con TAC tórax-abdomen-pelvis. CEA basal. RNM pélvica en cáncer de recto.",
            garantiaOportunidad: "Confirmación dentro de 30 días. Inicio de tratamiento dentro de 30 días post etapificación.",
            tratamiento: "Colon: colectomía + quimioterapia adyuvante (FOLFOX si etapa III). Recto: neoadyuvancia (QT-RT), resección anterior baja o amputación abdominoperineal.",
            seguimiento: "CEA cada 3 meses por 3 años. TAC cada 6-12 meses. Colonoscopía al año, luego cada 3-5 años."
        ),
        ProblemaGES(
            id: 71,
            nombre: "Cáncer de Ovario Epitelial",
            categoria: .oncologico,
            descripcion: "Neoplasia maligna del ovario de origen epitelial. Frecuentemente diagnosticado en etapas avanzadas.",
            poblacionObjetivo: "Personas de 15 años y más.",
            sospechaDiagnostica: "Distensión abdominal, dolor pélvico, masa anexial, ascitis, CA-125 elevado. Síntomas inespecíficos de inicio insidioso.",
            confirmacionDiagnostica: "Ecografía transvaginal, TAC abdomen-pelvis, CA-125. Confirmación histológica intraoperatoria o por biopsia.",
            garantiaOportunidad: "Confirmación dentro de 30 días. Inicio de tratamiento dentro de 30 días.",
            tratamiento: "Cirugía de citorreducción máxima (histerectomía, SOB, omentectomía, linfadenectomía). Quimioterapia: carboplatino + paclitaxel.",
            seguimiento: "CA-125 cada 3 meses. TAC cada 6 meses los primeros 2 años. Vigilancia clínica."
        ),
        ProblemaGES(
            id: 72,
            nombre: "Cáncer Vesical en Personas de 15 Años y Más",
            categoria: .oncologico,
            descripcion: "Neoplasia maligna de la vejiga urinaria. Hematuria es el síntoma cardinal.",
            poblacionObjetivo: "Personas de 15 años y más.",
            sospechaDiagnostica: "Hematuria macroscópica indolora, hematuria microscópica persistente, síntomas irritativos vesicales en fumadores.",
            confirmacionDiagnostica: "Cistoscopía con biopsia (RTU vesical). Etapificación con TAC urografía, RNM pélvica.",
            garantiaOportunidad: "Confirmación dentro de 30 días. Tratamiento dentro de 30 días.",
            tratamiento: "Superficial: RTU + BCG intravesical. Músculo-invasor: cistectomía radical + derivación urinaria. Quimioterapia neoadyuvante.",
            seguimiento: "Cistoscopía cada 3 meses el primer año, semestral hasta 5 años. Citología urinaria."
        ),
        ProblemaGES(
            id: 73,
            nombre: "Osteosarcoma en Personas de 15 Años y Más",
            categoria: .oncologico,
            descripcion: "Tumor óseo maligno primario más frecuente. Predomina en adolescentes y adultos jóvenes.",
            poblacionObjetivo: "Personas de 15 años y más.",
            sospechaDiagnostica: "Dolor óseo persistente (rodilla, fémur distal, tibia proximal, húmero), masa de partes blandas, fractura patológica.",
            confirmacionDiagnostica: "Radiografía (lesión ósea agresiva), RNM del segmento, TAC de tórax, biopsia ósea con estudio histopatológico.",
            garantiaOportunidad: "Confirmación dentro de 30 días. Inicio de tratamiento dentro de 30 días.",
            tratamiento: "Quimioterapia neoadyuvante, cirugía con preservación de extremidad o amputación, quimioterapia adyuvante. Rehabilitación.",
            seguimiento: "Control cada 3 meses con imágenes. TAC de tórax para vigilancia de metástasis pulmonares. Rehabilitación funcional."
        ),
        ProblemaGES(
            id: 74,
            nombre: "Tratamiento Quirúrgico de Lesiones Crónicas de la Válvula Aórtica",
            categoria: .cardiovascular,
            descripcion: "Reemplazo o reparación de válvula aórtica por estenosis o insuficiencia crónica significativa.",
            poblacionObjetivo: "Personas de 15 años y más.",
            sospechaDiagnostica: "Disnea de esfuerzo progresiva, angina, síncope de esfuerzo, soplo sistólico eyectivo o diastólico aspirativo aórtico.",
            confirmacionDiagnostica: "Ecocardiograma Doppler: estenosis aórtica severa (área < 1 cm², gradiente medio > 40 mmHg) o insuficiencia aórtica severa. Coronariografía preoperatoria.",
            garantiaOportunidad: "Confirmación dentro de 180 días. Cirugía dentro de 365 días desde indicación.",
            tratamiento: "Reemplazo valvular aórtico (prótesis mecánica o biológica). TAVI en pacientes de alto riesgo quirúrgico. Reparación valvular en seleccionados.",
            seguimiento: "Control cardiológico y ecocardiograma al mes, 6 meses y anual. Anticoagulación con AVK si prótesis mecánica."
        ),
        ProblemaGES(
            id: 75,
            nombre: "Trastorno Bipolar en Personas de 15 Años y Más",
            categoria: .saludMental,
            descripcion: "Trastorno del ánimo con episodios de manía/hipomanía y depresión. Requiere tratamiento de por vida.",
            poblacionObjetivo: "Personas de 15 años y más.",
            sospechaDiagnostica: "Episodios de ánimo expansivo, grandiosidad, disminución de necesidad de sueño, logorrea, conductas de riesgo, alternando con depresión.",
            confirmacionDiagnostica: "Evaluación psiquiátrica según criterios CIE-10/DSM-5. Descartar causas orgánicas y uso de sustancias.",
            garantiaOportunidad: "Confirmación dentro de 30 días. Inicio de tratamiento desde confirmación.",
            tratamiento: "Estabilizadores del ánimo: litio (primera línea), ácido valproico. Antipsicóticos atípicos en manía aguda. Lamotrigina para prevención de depresión.",
            seguimiento: "Control psiquiátrico mensual inicial, luego cada 2-3 meses. Litemia cada 3-6 meses. Función tiroidea y renal anual con litio."
        ),
        ProblemaGES(
            id: 76,
            nombre: "Hipotiroidismo en Personas de 15 Años y Más",
            categoria: .endocrinoMetabolico,
            descripcion: "Déficit de hormonas tiroideas. Causa más frecuente: tiroiditis de Hashimoto.",
            poblacionObjetivo: "Personas de 15 años y más.",
            sospechaDiagnostica: "Fatiga, aumento de peso, intolerancia al frío, constipación, piel seca, bradicardia, caída del cabello, alteraciones menstruales.",
            confirmacionDiagnostica: "TSH elevada con T4 libre baja (hipotiroidismo clínico) o T4 libre normal (subclínico). Anticuerpos anti-TPO.",
            garantiaOportunidad: "Confirmación dentro de 30 días. Inicio de tratamiento desde confirmación.",
            tratamiento: "Levotiroxina en ayunas (dosis según peso y severidad). Iniciar con dosis bajas en ancianos y cardiópatas.",
            seguimiento: "TSH a las 6-8 semanas de inicio o cambio de dosis. Una vez estable, control cada 6-12 meses."
        ),
        ProblemaGES(
            id: 77,
            nombre: "Hipoacusia Moderada, Severa y Profunda en Menores de 4 Años",
            categoria: .neonatalPediatrico,
            descripcion: "Pérdida auditiva moderada, severa o profunda en niños pequeños. Intervención precoz es crítica para el desarrollo del lenguaje.",
            poblacionObjetivo: "Menores de 4 años con hipoacusia moderada, severa o profunda bilateral.",
            sospechaDiagnostica: "No responde a sonidos, ausencia de balbuceo, no se orienta hacia la fuente sonora, retraso del lenguaje, screening auditivo neonatal alterado.",
            confirmacionDiagnostica: "Potenciales evocados auditivos de tronco cerebral (BERA/ABR). Emisiones otoacústicas. Impedanciometría. Audiometría condicionada.",
            garantiaOportunidad: "Confirmación dentro de 90 días. Implementación de audífono dentro de 30 días.",
            tratamiento: "Implementación de audífono bilateral precoz. Terapia auditivo-verbal intensiva. Implante coclear si hipoacusia severa-profunda sin beneficio con audífono.",
            seguimiento: "Control audiológico cada 3 meses. Evaluación de desarrollo del lenguaje. Ajuste de audífonos según crecimiento."
        ),
        ProblemaGES(
            id: 78,
            nombre: "Lupus Eritematoso Sistémico",
            categoria: .musculoesqueletico,
            descripcion: "Enfermedad autoinmune sistémica que puede afectar piel, articulaciones, riñón, SNC y otros órganos.",
            poblacionObjetivo: "Todas las personas.",
            sospechaDiagnostica: "Rash malar, fotosensibilidad, artritis, serositis, nefritis, citopenias, ANA positivo. Predominio en mujeres jóvenes.",
            confirmacionDiagnostica: "Criterios ACR/EULAR 2019 (score ≥ 10 con ANA positivo). Anti-dsDNA, complemento (C3, C4), anti-Smith.",
            garantiaOportunidad: "Confirmación dentro de 90 días. Inicio de tratamiento desde confirmación.",
            tratamiento: "Hidroxicloroquina para todos. AINES, corticoides según actividad. Inmunosupresores: azatioprina, micofenolato (nefritis), ciclofosfamida en formas graves.",
            seguimiento: "Control reumatológico cada 1-3 meses. Monitoreo renal, hematológico. Anti-dsDNA y complemento como marcadores de actividad."
        ),
        ProblemaGES(
            id: 79,
            nombre: "Tratamiento Quirúrgico de Lesiones Crónicas de las Válvulas Mitral y Tricúspide",
            categoria: .cardiovascular,
            descripcion: "Reparación o reemplazo quirúrgico de válvula mitral y/o tricúspide por lesión crónica significativa.",
            poblacionObjetivo: "Personas de 15 años y más.",
            sospechaDiagnostica: "Disnea de esfuerzo, ortopnea, fibrilación auricular, soplo pansistólico apical, edema periférico, signos de insuficiencia cardíaca.",
            confirmacionDiagnostica: "Ecocardiograma Doppler: insuficiencia mitral/tricuspídea severa o estenosis mitral significativa. Coronariografía preoperatoria.",
            garantiaOportunidad: "Confirmación dentro de 180 días. Cirugía dentro de 365 días desde indicación.",
            tratamiento: "Reparación valvular mitral (preferida sobre reemplazo). Reemplazo valvular con prótesis mecánica o biológica. Anuloplastía tricuspídea.",
            seguimiento: "Ecocardiograma al mes, 6 meses y anual. Anticoagulación con AVK si prótesis mecánica o fibrilación auricular."
        ),
        ProblemaGES(
            id: 80,
            nombre: "Tratamiento de Erradicación del Helicobacter Pylori",
            categoria: .digestivo,
            descripcion: "Erradicación de H. pylori en pacientes con úlcera péptica, linfoma MALT gástrico o familiares de primer grado de pacientes con cáncer gástrico.",
            poblacionObjetivo: "Personas con indicación de erradicación.",
            sospechaDiagnostica: "Úlcera péptica, dispepsia en < 40 años, antecedente familiar de cáncer gástrico, linfoma MALT, púrpura trombocitopénica inmune.",
            confirmacionDiagnostica: "Test de ureasa rápida en endoscopía, test de aire espirado (urea C13), antígeno fecal de H. pylori.",
            garantiaOportunidad: "Confirmación dentro de 30 días. Inicio de tratamiento dentro de 7 días.",
            tratamiento: "Terapia triple: IBP + amoxicilina + claritromicina por 14 días. Segunda línea: IBP + amoxicilina + levofloxacino o terapia cuádruple con bismuto.",
            seguimiento: "Test de erradicación (aire espirado o antígeno fecal) 4-6 semanas post tratamiento. Sin IBP por 2 semanas previas al test."
        ),
        ProblemaGES(
            id: 81,
            nombre: "Cáncer de Pulmón en Personas de 15 Años y Más",
            categoria: .oncologico,
            descripcion: "Neoplasia maligna pulmonar. Principal causa de muerte por cáncer a nivel mundial. Fuertemente asociado al tabaquismo.",
            poblacionObjetivo: "Personas de 15 años y más.",
            sospechaDiagnostica: "Tos persistente, hemoptisis, disnea, dolor torácico, baja de peso, nódulo o masa pulmonar en imágenes, síndrome de vena cava superior.",
            confirmacionDiagnostica: "TAC de tórax, broncoscopía con biopsia, biopsia percutánea, mediastinoscopía. Estudio histológico con marcadores moleculares (EGFR, ALK, PD-L1).",
            garantiaOportunidad: "Confirmación dentro de 30 días. Inicio de tratamiento dentro de 30 días post etapificación.",
            tratamiento: "Etapas I-II: cirugía (lobectomía + linfadenectomía) ± QT adyuvante. Etapa III: QT-RT. Etapa IV: QT, inmunoterapia, terapia dirigida según marcadores.",
            seguimiento: "TAC cada 3-6 meses los primeros 2 años, luego anual. Control clínico según síntomas."
        ),
        ProblemaGES(
            id: 82,
            nombre: "Cáncer de Tiroides Diferenciado y Medular en Personas de 15 Años y Más",
            categoria: .oncologico,
            descripcion: "Neoplasias malignas de tiroides: carcinoma papilar, folicular y medular. Generalmente buen pronóstico si tratamiento adecuado.",
            poblacionObjetivo: "Personas de 15 años y más.",
            sospechaDiagnostica: "Nódulo tiroideo palpable o incidental, adenopatía cervical, ronquera persistente, antecedente de radiación cervical, historia familiar de cáncer tiroideo.",
            confirmacionDiagnostica: "Ecografía tiroidea (clasificación TIRADS), punción aspirativa con aguja fina (PAAF) con citología (Bethesda). Calcitonina si sospecha de medular.",
            garantiaOportunidad: "Confirmación dentro de 30 días. Inicio de tratamiento dentro de 30 días.",
            tratamiento: "Tiroidectomía total o parcial según tamaño y tipo. Radioyodo (I-131) en diferenciado. Supresión de TSH con levotiroxina. Disección cervical si adenopatías.",
            seguimiento: "Tiroglobulina y ecografía cervical cada 6-12 meses. Cintigrafía con I-131 de seguimiento. Calcitonina en medular."
        ),
        ProblemaGES(
            id: 83,
            nombre: "Cáncer Renal en Personas de 15 Años y Más",
            categoria: .oncologico,
            descripcion: "Neoplasia maligna del riñón. El carcinoma de células renales (células claras) es el tipo más frecuente. Frecuentemente diagnosticado de forma incidental.",
            poblacionObjetivo: "Personas de 15 años y más.",
            sospechaDiagnostica: "Hematuria macroscópica, dolor lumbar, masa palpable en flanco (tríada clásica infrecuente). Hallazgo incidental en imágenes abdominales. Síndromes paraneoplásicos.",
            confirmacionDiagnostica: "TAC de abdomen y pelvis con contraste (masa renal sólida captante). Etapificación con TAC de tórax. Biopsia en casos seleccionados.",
            garantiaOportunidad: "Confirmación dentro de 30 días. Inicio de tratamiento dentro de 30 días post etapificación.",
            tratamiento: "Nefrectomía radical o parcial según tamaño y localización. Terapias sistémicas en enfermedad avanzada: antiangiogénicos, inmunoterapia (nivolumab + ipilimumab), inhibidores de tirosina quinasa.",
            seguimiento: "TAC cada 3-6 meses los primeros 2 años, luego anual. Control de función renal. Vigilancia del riñón contralateral."
        ),
        ProblemaGES(
            id: 84,
            nombre: "Mieloma Múltiple en Personas de 15 Años y Más",
            categoria: .oncologico,
            descripcion: "Neoplasia de células plasmáticas con producción de inmunoglobulina monoclonal. Causa lesiones óseas líticas, anemia e insuficiencia renal.",
            poblacionObjetivo: "Personas de 15 años y más.",
            sospechaDiagnostica: "Dolor óseo (especialmente dorsal), anemia inexplicada, insuficiencia renal, hipercalcemia, infecciones recurrentes, VHS muy elevada.",
            confirmacionDiagnostica: "Electroforesis de proteínas con peak monoclonal, inmunofijación, cadenas livianas libres, mielograma (≥ 10% células plasmáticas), imágenes óseas.",
            garantiaOportunidad: "Confirmación dentro de 30 días. Inicio de tratamiento dentro de 30 días.",
            tratamiento: "Inducción: VRd (bortezomib, lenalidomida, dexametasona). Trasplante autólogo en elegibles. Mantención con lenalidomida.",
            seguimiento: "Electroforesis y cadenas livianas cada 1-2 meses. Evaluación de respuesta según criterios IMWG. Vigilancia de complicaciones óseas."
        ),
        ProblemaGES(
            id: 85,
            nombre: "Enfermedad de Alzheimer y Otras Demencias",
            categoria: .neurologico,
            descripcion: "Deterioro cognitivo progresivo que afecta la funcionalidad. Incluye Alzheimer, demencia vascular, cuerpos de Lewy y otras.",
            poblacionObjetivo: "Todas las personas.",
            sospechaDiagnostica: "Pérdida de memoria progresiva, desorientación temporal-espacial, dificultad en tareas habituales, cambios de personalidad, juicio alterado.",
            confirmacionDiagnostica: "Evaluación neuropsicológica (MMSE, MoCA). RNM cerebral (atrofia hipocampal). Laboratorio para descartar causas reversibles (TSH, B12, RPR, VIH).",
            garantiaOportunidad: "Confirmación dentro de 90 días. Inicio de tratamiento desde confirmación.",
            tratamiento: "Inhibidores de colinesterasa (donepezilo, rivastigmina) en demencia leve-moderada. Memantina en moderada-severa. Manejo conductual no farmacológico.",
            seguimiento: "Control cada 3-6 meses. Evaluación cognitiva y funcional periódica. Apoyo al cuidador. Planificación de cuidados avanzados."
        ),
        ProblemaGES(
            id: 86,
            nombre: "Atención Integral de Salud en Agresión Sexual Aguda",
            categoria: .otros,
            descripcion: "Atención de emergencia integral (médica, psicológica, legal) a víctimas de agresión sexual reciente.",
            poblacionObjetivo: "Todas las personas víctimas de agresión sexual aguda (dentro de las primeras 72 horas).",
            sospechaDiagnostica: "Relato de agresión sexual reciente. Consulta en servicio de urgencia por violencia sexual.",
            confirmacionDiagnostica: "Evaluación clínica, toma de muestras médico-legales, constatación de lesiones, evaluación psicológica de urgencia.",
            garantiaOportunidad: "Atención inmediata en servicio de urgencia.",
            tratamiento: "Profilaxis de ITS (VIH, hepatitis B, sífilis, gonorrea, clamidia), anticoncepción de emergencia, atención psicológica de crisis, toma de muestras legales.",
            seguimiento: "Control a las 2 semanas, 1 mes, 3 meses y 6 meses. Serología de control. Apoyo psicológico continuado. Derivación a red de protección."
        ),
        ProblemaGES(
            id: 87,
            nombre: "Rehabilitación SARS-CoV-2",
            categoria: .respiratorio,
            descripcion: "Programa de rehabilitación integral para pacientes con secuelas persistentes post infección por SARS-CoV-2 (COVID prolongado).",
            poblacionObjetivo: "Personas con secuelas funcionales post COVID-19 que persisten más allá de 12 semanas.",
            sospechaDiagnostica: "Disnea persistente, fatiga crónica, deterioro de capacidad funcional, alteraciones cognitivas ('niebla mental'), desacondicionamiento físico post COVID.",
            confirmacionDiagnostica: "Antecedente documentado de infección por SARS-CoV-2. Evaluación funcional: espirometría, test de marcha de 6 minutos, evaluación de calidad de vida.",
            garantiaOportunidad: "Inicio de rehabilitación dentro de 30 días desde la derivación.",
            tratamiento: "Rehabilitación pulmonar, kinesioterapia respiratoria y motora, terapia ocupacional, fonoaudiología si disfagia, apoyo psicológico.",
            seguimiento: "Evaluación funcional cada 3 meses. Espirometría de control. Evaluación de reintegro laboral. Alta cuando se alcancen objetivos funcionales."
        ),
        ProblemaGES(
            id: 88,
            nombre: "Tratamiento Farmacológico Post Hospitalización por Cirrosis",
            categoria: .digestivo,
            descripcion: "Tratamiento farmacológico ambulatorio para personas hospitalizadas por descompensación de cirrosis hepática.",
            poblacionObjetivo: "Personas hospitalizadas por descompensación de cirrosis hepática (ascitis, peritonitis bacteriana espontánea, hemorragia variceal, encefalopatía hepática).",
            sospechaDiagnostica: "Paciente con cirrosis conocida que presenta descompensación: ascitis a tensión, hemorragia digestiva variceal, encefalopatía hepática, peritonitis bacteriana espontánea.",
            confirmacionDiagnostica: "Diagnóstico de cirrosis establecido (clínico, imagenológico o histológico). Hospitalización por evento de descompensación documentado. Clasificación Child-Pugh.",
            garantiaOportunidad: "Acceso a tratamiento farmacológico desde el alta hospitalaria.",
            tratamiento: "Según tipo de descompensación: diuréticos (espironolactona, furosemida), lactulosa, rifaximina, betabloqueadores no selectivos (profilaxis de hemorragia variceal), albúmina, norfloxacino profiláctico.",
            seguimiento: "Control hepatológico dentro de los primeros 7-14 días post alta. Luego mensual. Evaluación para trasplante hepático. Monitoreo de función hepática y renal."
        ),
        ProblemaGES(
            id: 89,
            nombre: "Tratamiento Hospitalario para Menores de 15 Años con Depresión Grave Refractaria o Psicótica con Riesgo Suicida",
            categoria: .saludMental,
            descripcion: "Hospitalización psiquiátrica para niños y adolescentes con depresión severa que no responde a tratamiento ambulatorio, con síntomas psicóticos o riesgo suicida inminente.",
            poblacionObjetivo: "Menores de 15 años con depresión grave refractaria a tratamiento ambulatorio, depresión con síntomas psicóticos, o depresión con riesgo suicida alto.",
            sospechaDiagnostica: "Ideación suicida activa con plan, intento suicida reciente, síntomas psicóticos (alucinaciones, delirios), deterioro funcional severo, falla a tratamiento ambulatorio adecuado.",
            confirmacionDiagnostica: "Evaluación psiquiátrica especializada. Criterios de depresión grave según CIE-10/DSM-5. Evaluación de riesgo suicida con instrumentos validados. Descarte de causas orgánicas.",
            garantiaOportunidad: "Hospitalización dentro de 24 horas desde la indicación.",
            tratamiento: "Hospitalización en unidad de psiquiatría infanto-juvenil. Farmacoterapia (ISRS, ajuste de dosis), psicoterapia intensiva, contención de crisis, intervención familiar. Terapia electroconvulsiva en casos excepcionales.",
            seguimiento: "Plan de egreso con control psiquiátrico dentro de 7 días post alta. Seguimiento ambulatorio intensivo. Coordinación con red educacional. Prevención de reingreso."
        ),
        ProblemaGES(
            id: 90,
            nombre: "Cesación del Consumo de Tabaco en Personas de 25 Años y Más",
            categoria: .otros,
            descripcion: "Programa de apoyo integral para dejar de fumar. Incluye consejería, terapia conductual y tratamiento farmacológico.",
            poblacionObjetivo: "Personas de 25 años y más fumadoras que deseen dejar de fumar.",
            sospechaDiagnostica: "Fumador activo que expresa deseo de cesación o que presenta patología asociada al tabaquismo. Evaluación con test de Fagerström para dependencia a nicotina.",
            confirmacionDiagnostica: "Confirmación de tabaquismo activo. Evaluación de grado de dependencia (test de Fagerström). Evaluación de motivación (estadios de cambio de Prochaska).",
            garantiaOportunidad: "Inicio de intervención dentro de 30 días desde la solicitud.",
            tratamiento: "Consejería breve (ABC), terapia conductual grupal o individual, terapia de reemplazo de nicotina (parches, chicles), vareniclina o bupropión según evaluación.",
            seguimiento: "Seguimiento a las 1, 2, 4, 8 y 12 semanas. Evaluación de abstinencia. Manejo de recaídas. Seguimiento hasta completar 6 meses sin fumar."
        ),
    ]
}
